version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 10
build:
  build:
    commands:
      - echo nothing to do yet
  artifacts:
    files:
      - index.html
      - favicon.ico
      - Steven_Beard.pdf
      - styles/*
      - images/*
