version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
build:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - Steven_Beard.pdf
    - styles/*
    - images/*
    - dist/bundle.js
