version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
build:
  run-as: root
  commands:
    - npm install
    - npm run webpack
    - echo did webpack build?
artifacts:
  files:
    - index.html
    - favicon.ico
    - Steven_Beard.pdf
    - styles/*
    - images/*
    - dist/bundle.js
